version: 0.2
env:
  parameter-store:
    wiz_cred: "Credentials"
phases:
  build:
    commands:
      - echo Entered the build phase...
      - echo "Wiz credentials ${wiz_cred}"

artifacts:
  files:
    - '**/*'
