version: 0.2
env:
  variables:
    var: Testing-wiz
    
  parameter-store:
    wiz_cred: "Credentials"
phases:
  pre_build:
    commands:
      - echo "Getting paramtere store value.."
      - SECRET=${wiz_cred}
      - echo The value of parameter store is $SECRET
  build:
    commands:
      - echo Entered the build phase...
      - echo "Wiz credentials ${wiz_cred}"
      - echo value of var is $var
      - echo done

artifacts:
  files:
    - '**/*'
