version: 0.2
env:
  parameter-store:
    ID: "client_id"
    SECRET: "client_secret"
phases:
  pre_build:
    commands:
      - echo Installing wizcli
      - curl -o wizcli https://wizcli.app.wiz.io/wizcli
      - file wizcli
      - uname -a
      - chmod +x wizcli
      - ls -l wizcli
      - echo $PWD
  build:
    commands:
      - echo Entered the build phase...
      - ./wizcli auth --id $ID --secret $SECRET
      - ./wizcli iac scan --path s3.json
      - echo $?
