version: 0.2
env:
  variables:
    var: Testing-wiz
    
  parameter-store:
    wiz_cred: "Credentials"
phases:
  pre_build:
    commands:
      - echo Installing wizcli
      - curl -o wizcli https://wizcli.app.wiz.io/wizcli
      - chmod +x wizcli
      - ls -l wizcli
  build:
    commands:
      - echo Entered the build phase...
      - echo "Wiz credentials ${wiz_cred}"
      - echo value of var is $var
      - echo done

artifacts:
  files:
    - '**/*'
