version: 0.2
env:
  variables:
    var: Testing-wiz
  parameter-store:
    ID: "Credentials"
    SECRET: "fortesting"
phases:
  pre_build:
    commands:
      - echo Installing wizcli
      - curl -o compliancecli https://wizcli.app.wiz.io/wizcli
      - file wizcli
      - uname -a
      - chmod +x compliancecli
      - ls -l compliancecli
      - echo $PWD
  build:
    commands:
      - echo Entered the build phase...
      - ./compliancecli auth --id $ID --secret $SECRET
      - echo value of var is $var
      - echo done
   

artifacts:
  files:
    - '**/*'
