version: 0.2
env:
  variables:
    var: Testing-wiz
    
  parameter-store:
    ID: "Credentials"
    SECRET: "fortesting"
phases:
  pre_build:
    commands:
      - echo Installing wizcli
      - curl -o wizcli https://wizcli.app.wiz.io/wizcli
      - chmod +x wizcli
      - ls -l wizcli
  build:
    commands:
      - echo Entered the build phase...
      - wizcli auth --id $ID --secret $SECRET
      - echo value of var is $var
      - echo done
   

artifacts:
  files:
    - '**/*'
